# Generated by Django 3.1 on 2020-08-07 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('type_question', models.CharField(choices=[('BOOLEAN', 'BOOLEAN'), ('MULTIPLE CHOICE, ONE ANSWER', 'MULTIPLE CHOICE, ONE ANSWER'), ('MULTIPLE CHOICE, MORE THAN ONE ANSWER', 'MULTIPLE CHOICE, MORE THAN ONE ANSWER'), ('MULTIPLE CHOICE, MORE THAN ONE ANSWER, ALL HAS TO BE CORRECT', 'MULTIPLE CHOICE, MORE THAN ONE ANSWER, ALL HAS TO BE CORRECT')], max_length=200)),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
