# Generated by Django 3.1 on 2020-08-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_remove_lesson_questions'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ManyToManyField(to='lessons.Lesson'),
        ),
    ]
