# Generated by Django 3.1 on 2020-08-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200809_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_answer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
