# Generated by Django 3.1 on 2020-08-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200809_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_answer',
            field=models.CharField(default='correct answer', max_length=200),
        ),
    ]
